apiVersion: v1
kind: Secret
metadata:
    name: lldaps-config
stringData:
    jwtSecret: ENC[AES256_GCM,data:vVweoHf7Q4046v9nHYQYrirZLZn24IYPaprmtfAFTLo=,iv:ebpPIGIRJzfeWJH1Y+nTJtZ42hQ9araZldag9yGz/98=,tag:PtyALWe8+bH7HyHaQ9NL4A==,type:str]
    ldapUserPass: ENC[AES256_GCM,data:yuU6vpkJAZI=,iv:js8D/CXr2eQPm8CwDVJU5y61aRlQeUzZZhiTpNDYaQI=,tag:RbqnnK3zysAtGwTe8U5GtQ==,type:str]
    keySeed: ENC[AES256_GCM,data:KBY70bRRY2wSg+sYa9hNZgRbhk+cJ7i+ZthQ/rg0tks=,iv:uy+/a8Akq4WZNNpY3aTCUjnOOXTqFEza5oAxkKvLUAQ=,tag:9owF50JL0eBsgkuKRokhOA==,type:str]
sops:
    age:
        - recipient: age157ahydv9rlk6p5g3l93p84nrlw7a5ndjl2yakvmy2n78hcdeey5s74xwf2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJL1AvTTdqR3lWYndRanJC
            bkhFWmJrSHBLZ3hHUnI2alEydlFnNCtIV2xBCmRzbUdhbjkxcFdkWE5rZnFPSlhi
            d3NrOWRHWWNmYktxSjNsVDROTW5VSm8KLS0tIHZGaXFEZkxYMndqZ1l0RGQvRWRW
            NDR2aTNlNkpPVG5Qa09yTnZyN2VaSGcKOXI2hx+nlK/ZyM8wZ36x980GXukXm7Ur
            VPuD7l6x47pSZ0f2ek3Y7tWsnd/cH6BUUnQviWRZqsSEL4X/a9UN+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-05T15:15:37Z"
    mac: ENC[AES256_GCM,data:Nls9PN0xQeRjIf7zbKrw03V+y2LZZjpmVFVhHazP/Gdz8X4t7hRfZEODRjAVUZ2PBMRO7P4MAei8LIWFLfpOP3eEhWATb9wJkXwteK653Vk98jGm/kk/6XuA/KUmqAPS2BFW11PtlpPfWLIxWytwCzph0v204fxViCyypuMQoxg=,iv:BjpI7B3ozOc1WTTnIo7skWqxHf4zu71fMeFb0suQnnY=,tag:zotl8QWdrMD8C5rp4C+Hfw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
