apiVersion: v1
data:
  ca-cert-PROXY.pem: |
    -----BEGIN CERTIFICATE-----
    MIIENDCCAxygAwIBAgISerW/TqZ9iFDCXu0KPIOeYn/JMA0GCSqGSIb3DQEBCwUA
    MHUxCzAJBgNVBAYTAk5MMRUwEwYDVQQIEwxadWlkLUhvbGxhbmQxETAPBgNVBAcT
    CERlbiBIYWFnMQ4wDAYDVQQKEwVJTlNJTTEQMA4GA1UECxMHWnNjYWxlcjEaMBgG
    A1UEAxMRSU5TSU0gWnNjYWxlciBDQTIwHhcNMjUwODA1MDcxNDAxWhcNMjUwODE5
    MDgxNDAxWjBPMR8wHQYDVQQDExZ1bml4LnN0YWNrZXhjaGFuZ2UuY29tMRUwEwYD
    VQQKDAxac2NhbGVyIEluYy4xFTATBgNVBAsMDFpzY2FsZXIgSW5jLjCCASIwDQYJ
    KoZIhvcNAQEBBQADggEPADCCAQoCggEBAPEUd3Hf2zHT+4tTadaIQHTOOWwD7Yhd
    RgBxcMOsWK9bTZwM9ksakSV4PmCGzp23oHee/RljIqH3/xYOw5joODspnZG8F3Kp
    7gAFkUOT6pW+rUREExLgoBft88x7MnX7BLzbFlw1i33US2FNo22fwxXDxwlXdv4h
    Sno0a4YG9FOwCatMqigYM2TivqrwUVIjrUerlLa396kfGz8IYvo2bsugTaxJGOBg
    2pLs/+t40ptLvTZnvglSJv0bw820Fi9PepD7gIGvnnzvS81shs7z2sk3dQeuhU3T
    5k+0tZnT8mjQuHBerQpiAvLmXIHpD5zR4QvYjK+PBzAp6HFbVxXru4kCAwEAAaOB
    4zCB4DATBgNVHSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMCEGA1UdEQQa
    MBiCFnVuaXguc3RhY2tleGNoYW5nZS5jb20wDgYDVR0PAQH/BAQDAgWgMEgGA1Ud
    HwRBMD8wPaA7oDmGN2h0dHA6Ly9nYXRld2F5LnpzY2xvdWQubmV0L3pzY2FsZXIt
    enNjcmwtOTMzMzY0LTI3NS5jcmwwHQYDVR0OBBYEFCcT5/5XxxGMxxnHmL4sHJ1I
    MKjSMB8GA1UdIwQYMBaAFFvdUl4ZQnDqOsnquiQOI6QVi0pEMA0GCSqGSIb3DQEB
    CwUAA4IBAQCY+E2O+XdG28AVA0NygFTTkJfYTGgUpV+3CXE3RjbsybOY+e28PDr9
    5UWZR08BfCKK7mnNzj30r8GYTf8nvc0JUoVkI2WXTG4JxBXeiaI50odnpe9Hy+wt
    PqWHW6xh+DemaCZh+hjXSiA27Mgq5E94lCWchmgmeQ12kbNqAnV0aSyrh0xd62pD
    7r8755W1MhGJxyvMIa0mKqyoT1vVwaM+XL9m6b3RuvG4fSEbVv6BPorhAi/IScPc
    MyiUeiA0IFCBiCZCqslaG+lfmBZ4fTeY/T4eiedDC1l25bA7ZVI+MCms/A2feFsf
    q4TB9WRe9y0yADbeoBLXvi1s6wc9tZ+W
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIFGTCCAwGgAwIBAgISESFdGq3f7PklUzL5l0ASs8awMA0GCSqGSIb3DQEBCwUA
    MF4xDjAMBgNVBAoTBUlOU0lNMREwDwYDVQQLEwhTZXJ2aWNlczEgMB4GA1UECxMX
    Q2VydGlmaWNhdGUgQXV0aG9yaXRpZXMxFzAVBgNVBAMTDklOU0lNIFJvb3QgQ0Ey
    MB4XDTE4MDEyNTAwMDAwMFoXDTMxMTExMDAwMDAwMFowdTELMAkGA1UEBhMCTkwx
    FTATBgNVBAgTDFp1aWQtSG9sbGFuZDERMA8GA1UEBxMIRGVuIEhhYWcxDjAMBgNV
    BAoTBUlOU0lNMRAwDgYDVQQLEwdac2NhbGVyMRowGAYDVQQDExFJTlNJTSBac2Nh
    bGVyIENBMjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMol9CQlM1vR
    gYw1Eik+kypsVzo5dI5rHSSyvVf0o+9Pv+siC/UbJKmH3d1ydBnhOV1lgA6nC6fw
    r8Z3w7kbVYEuqdHvo8mchr0OJ5KuX/yOIqG24lZ/VONV18gD2T2L5HYKOqJHzSSz
    SvcZFM+tY8wgZ6hhHGb4nFGot/Ys9POuAsGv2Tn2j/+lVIfRiAbcAbYyXGPh2urt
    F3QXcFxn6D/XubX8zwAIsYhmqZQHIC+fyC9k5RzlbnT6eDu1WfIM++Z7Rwtc99iT
    +9mm135dkMFmhFlEOvYSxGTlIGIqfJzD/uOffyecESBaFH9l+UPUv47C/PANkyqs
    STQTYYfb0jECAwEAAaOBuTCBtjAOBgNVHQ8BAf8EBAMCASYwEQYDVR0gBAowCDAG
    BgRVHSAAMBIGA1UdEwEB/wQIMAYBAf8CAQAwPQYDVR0fBDYwNDAyoDCgLoYsaHR0
    cDovL2NybDIuaW5zaW0uYml6L2luc2ltL2NybDIvcm9vdGNhMi5jcmwwHQYDVR0O
    BBYEFFvdUl4ZQnDqOsnquiQOI6QVi0pEMB8GA1UdIwQYMBaAFGzVtC+BMpeL20hB
    7fUgGOre6RhuMA0GCSqGSIb3DQEBCwUAA4ICAQANvuSKUtTYZ4VHdCor9oBMUI2y
    NwsHxQUuBfigykbf8cQ75nlmFzNRux9U8NYMu8iDx/KPyr1ZNzLK2gA0QP/iu6UZ
    pLXY5+D4M1W41CBBGHbtBLcGADa7s94ZfF91PkViQZpr5YYTe75p9GJF9b6odVUc
    FvYYMz+gtOLEiajeiwQhskbEu8evysAKAh+KCCBl/QDg8z22kG+trvaV7OrkaNMe
    5/3Zb93INs1RDqqWNuzchPRH7jaRsWjiWsuVTgdLvV/PlZPy4kTq6DOWIn6WqKOf
    mFYDKmOQYm+EAnOR/xq4mzZVvfJpZ6dFseMPicJT2UeWA4KiK/mI5kRh9Ukh0NJ7
    gc/0c4phOc/3sWKGASB0QTDht67CYBYQQ3u800mk+nBazLlmemz/b+JUFoV7zC8H
    yxuHUt/tc8lWkCb7BWCWgR3yVfdmoIJFDT/spvkeaGTJdQ1k4YwcORNXv1ZGLYUu
    3/IaaA0LjSBuDmZId/rKtFsyYqc1Vne3+zqzIZF76038t7VBo9sLsFPGyMETDGhW
    GoTIIW+Nlt+n7RGQSV3Xdxr3jc0cyLvN9E+cR0QNP6zLX+9SQ7zinfeCTN/X6tK+
    Q3V7CwnUtoOnPAZKVgUcXKHTCopRS+VKoTJ34DXxLHkLMsfEVkK7PSdPjBBhsYmW
    asXNGi2ayoGd0f3Ucg==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIGAzCCA+ugAwIBAgISESAAkX/FlQZFqSYU6J6oVNYNMA0GCSqGSIb3DQEBCwUA
    MF4xDjAMBgNVBAoTBUlOU0lNMREwDwYDVQQLEwhTZXJ2aWNlczEgMB4GA1UECxMX
    Q2VydGlmaWNhdGUgQXV0aG9yaXRpZXMxFzAVBgNVBAMTDklOU0lNIFJvb3QgQ0Ey
    MB4XDTExMTExMDAwMDAwMFoXDTMyMDMxMDAwMDAwMFowXjEOMAwGA1UEChMFSU5T
    SU0xETAPBgNVBAsTCFNlcnZpY2VzMSAwHgYDVQQLExdDZXJ0aWZpY2F0ZSBBdXRo
    b3JpdGllczEXMBUGA1UEAxMOSU5TSU0gUm9vdCBDQTIwggIiMA0GCSqGSIb3DQEB
    AQUAA4ICDwAwggIKAoICAQDBZ8FDKgPV4Le+FzWs3CDIbEdnwmeeLQQW+3e9nnbt
    9j1D3o/f+D5Gposb7rVST8YEbw0yiNplsoOLlPc7XzmzffpWfNqOekR98bl8idJc
    pB49Rwv7s+Uu7FmxV3cXL3+kgpsPdpz5M0xrtRLFbGJdezaqI3kFlMRgMyjjn7w2
    TBRPu4/di0XJm2EGtvfmOmIP8pzWCpucXFwwcuSjmHAMQHNzLv2N41jqCX3pAUNY
    C9W4mHuc3hqYGB1IrZfHYRc3mOaHRbov62MCAeLyHV6I27iPHDytuTwZqdYZkaTp
    i+tErjtmYMpfhDHVzsOXBlALAkOvv3lRRA86yoCdukCLz0ID8/bOfEuB7EViWa0y
    8SKBglvSNjY2I06PwiwJ6Fpvz8qSsC9elVNO0Dc/MOUjyIAsMQ8MLjaqMaEFnlcf
    ynhWCGhoD0nPDzP5Moicr0+zGOvOgD49YVqC4vSl9v6O4t5IA1+QZ6hCiK4zYCHE
    FQCc90ywQDlZHdebyvnCYi9pdF9vqH9FBBpzAlz6OjJwn850z1+m6s7FPmopDIpI
    f23G0Wl8/21E87B6xTteYioJ3vGV+23wajZOMy2+c1eiYrRboaItaomCW/OnssZj
    6hKRRhx8Nk3qFwnXuOJHkSxx8JTeYV0umfmw7JXGM//nIptW/YHWKyQWvP+lEGhm
    xQIDAQABo4G6MIG3MA4GA1UdDwEB/wQEAwIBBjBRBgNVHSAESjBIMEYGBFUdIAAw
    PjA8BggrBgEFBQcCARYwaHR0cDovL3BraTIuaW5zaW0uYml6L2luc2ltL3BraTIv
    Y3BzX3Jvb3RjYTIucGRmMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYEFGzV
    tC+BMpeL20hB7fUgGOre6RhuMB8GA1UdIwQYMBaAFGzVtC+BMpeL20hB7fUgGOre
    6RhuMA0GCSqGSIb3DQEBCwUAA4ICAQAEjO/dTvxST0M5+bs/SOP+7Z5UNBohQw2w
    yN8jCK70PnxaKyOBtCORbojpZlKA9dv8A/bpGyUE+NiSHWFRD+pY3FXZ/y5lvXV7
    fv4jZgPd5YjL1OyVGQGEUJL3JzwnwvErjB8epGDtiKXooXv/WHJ1wcRu4V/t1WtK
    eyfb/ajDpCMaIblLfjlUcuHllqo4uhKEdRrG29cTmdlvT5fBgzlVHvNzqc+jLbaC
    WytcrlIW99CsOgEoykPVxlwX/SkYbcRVBWlb3PU6BLcALK1JjnQXRcioEIyAq4W2
    3GtLY6ykh+divWRVvVVwp/ZTbdokZ1D3c2oL4ZxpUJbmaQBtO1JmAjdb6Ie2mgvz
    8lEk5XU5jC96UFKhw2hTNQU8JN5hF8gYaERHWMfYEdTIx1TMaz0zFH8cbPCiQawB
    1xpN3lZhUX6XB5+EQRHZn7eAEAL8duWv1JzRZUg17fJ6Im1umB2qh8InCZ7cLRBh
    6jrTNBIriNMQXeJNHHQJLu/jJeI2xvhj1r8t8yAalfK5euwpZ8aPV21D9w5LdPxC
    gKck84s6v+tp2aGHRW+3MGPo5tFYpQaW+YvO9LmrqXsmhHfGxTQuIVOAkYiTr8BX
    R70+pbXIAs3qqo7MaDvWQYojsOtMBHjyPiqAkLKijYU9IpzFZxKTloAP4PI7Cijo
    +7l61HbHxw==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: ca-pemstore
  namespace: flux-system
