apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-ca.yaml
  - gotk-components.yaml
  - gotk-sync.yaml
patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: all
      spec:
        template:
          spec:
            containers:
              - name: manager
                volumeMounts:
                - name: ca-pemstore
                  mountPath: /etc/ssl/certs/ca-cert-PROXY.pem
                  subPath: ca-cert-PROXY.pem
                  readOnly: false
                env:
                  - name: "HTTPS_PROXY"
                    value: "http://10.206.103.25:8080/"
                  - name: "NO_PROXY"
                    value: ".cluster.local.,.cluster.local,.svc,10.96.0.1"
            volumes:
              - name: ca-pemstore
                configMap:
                  name: ca-pemstore
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/part-of=flux
